collections:
  posts:
    permalink: /1/125/:title/

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
    values:
      layout: main

exclude:
  - Rakefile
  - gems.locked
  - gems.rb
  - origs
  - tmp

timezone: UTC

url: https://chastell.net
