source 'https://rubygems.org'

gem 'exifr',                '~> 1.2'
gem 'fastimage',            '~> 1.5'
gem 'middleman',            '~> 3.4'
gem 'middleman-blog',       '~> 3.5'
gem 'middleman-gh-pages',   '~> 0.3.0'
gem 'middleman-livereload', '~> 3.4'
gem 'pry',                  '~> 0.10.0'
gem 'slim',                 '~> 3.0'
